### ISSUE TITLE
Release v1.1

### ISSUE THREAD

**Issue by f3l1x** [componette/componette.com#66]
# Roadmap

- [ ] about page #35 -> [to v1.2](https://github.com/componette/componette.com/issues/79)
- [x] report addon #56 
- [x] editorconfig #57 
- [x] commit composer.lock #59
- [x] replace nette/application by symfony/console #58
- [x] create migration #61, #62  
- [x] separate docker files
- [x] addon releases #28 
- [ ] addon stats #37 -> [to v1.2](https://github.com/componette/componette.com/issues/79)
- [x] fix image replacing - PR #64
- [x] update to Nette 2.4
- [x] update docker containers (Nginx, PHP)
- [ ] create test sandbox to help others to contribute-> [to v1.2](https://github.com/componette/componette.com/issues/79)

-----

- [ ] replace nextras/orm with doctrine (maybe in the future)
- [ ] fix HTTP2 + HTTPS + ALPN + HSTS (#34) (in the near future)

**Comment by JanTvrdik** [comment]
>  replace nextras/orm with doctrine

Reason? :smile:

**Comment by hrach** [comment]
> replace nextras/orm with doctrine

do have have some bad experience with nextras orm? :-) Plase, share :)

**Comment by f3l1x** [comment]
@JanTvrdik 

>>replace nextras/orm with doctrine

>Reason?

Please, if you really want to known reason, try to write more then just "reason".

-----

@hrach 

I like nextras/orm. But I want to use symfony/events, symfony/console, doctrine/console (for schema generating/updating). There're Kdyby/Events and Kdyby/Console packages. And it makes me sence to use Kdyby/Doctrine, with all that stuff. For more, I think it increase interest for PR/Isssues/Contributing Because Doctrine is quite more popular. 

I use nextras/orm for my personal project and can't be more happier. :-) You see it on issues reported by me. :100:  

-----

Please do not start flaming. Just be cool. :-)

**Comment by hrach** [comment]
@f3l1x 
> Please, if you really want to known reason, try to write more then just "reason".
> Please do not start flaming. Just be cool.

Does not seem cool from you ... much ;)

---

- Nextras Orm works great with Kdyby/Events & Kdyby/Console. There is no deal-breaker.
- Nextras Orm doesn't (natively) support generating of schema based on the entities, or updating entities by the schema. That's true fact. Personally, I think it's not so needed & useful.
- Doctrine Migrations are ****. Nextras Migrations are great, since this projects doesn't use them, I'm not sure how much experience you have with them.

**Comment by f3l1x** [comment]
@hrach Well, I've thought about it once again. 

All that things I mentioned above are only nice-to-have, it could work with nextras/orm. In the future, I would like to track/persist entities to elasticsearch. I do not have a lot experience but I like an idea of one entity with more annotations. I think Doctrine has a package for it (https://github.com/doctrine/search). It's a bigger reason then just I like it more. Does it make a sense? What do you think?

**Comment by f3l1x** [comment]
Finally closed. https://github.com/componette/componette.com/commit/e383b7b29d063d57de3e3040c9696119b690b00d
